### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Cetty** [Joecorleone/Derailer#1]
- [x] Black screen after resume
- [x] Moving play button
- [x] Too long thinking time
- [x] Warning for too few players 
- [x] Fix Smoke animation
- [x] Implement game option: Obstacles
- [x] Implement game option: Draw
- [x] Implement game option: Order
- [x] Not clear that more colors are available
- [x] Rotating tile not clear
- [x] Show tiles instead of text "4" & "8"
- [x] Waiting time for AI during place selection
- [ ] Speed up train for long drives
- [ ] Review to implement status bar instead of pop up
- [x] Error when two players lose at same time
- [x] Sounds
- [x] Music
- [x] Options for music and sounds
- [x] #2 
- [ ] Distance meter
- [x] Improve tablet support
- [x] Add animations for all themes
- [x] Replace pngs with vectordrawables (aside from tiles) and 9 patches
- [x] Fix bug: crash when the last two player crash at the same time
- [ ] #5
- [x] #6
- [ ] #7
- [ ] #8
- [x] Add translations: German, Spanish, Japanese, French, Italian
- [x] Implement game option: Collision on/off
- [ ] Implement game option: Outer border on/off
- [x] Display current and relevant game options during game
- [ ] Add time delay after explosion as it it mostly disturbed by next phase message
- [x] Make Game settings screen scrollable (not all settings displayed on small devices)
- [x] Make Layout of game options a grid
- [ ] #9 
- [ ] Add check for cart-cart collision on different path to AI
- [ ] Add indicator for new themes in main menu
- [ ] Online-Multiplayer via Google API

**Comment by Joecorleone** [comment]
- Alert dialog added to warn when too few players are selected
- Added left and right arrow to player/colorselection recyclerview
- Replaced text indicating the selected number of connections with images
- Implemented displaying the player number in a grid next to the play button
- Added a rotation indicator to the most recent placed card
- Potentially fixed bug "crash when last two players crash at the same time"
- Added function to allow disabling an Option
- Added onResume to resume GameView
- Fixed smoke animation (negative alpha values not allowed)
- Added explosion animation and sprite
- Added Option to enable/disable Collision
- Added dialog to manage sound (music and sfx)
- Added sound effects for all UI elements and cart movement
- Added option to switch off music and sound effects as a dialog
- Added horn button
- Added background music and volume slider
- Added elements to display selected options in game

**Comment by Joecorleone** [comment]
Todo list for release:

- [x] revise Badger's Burrow store background graphic
- [x] Improve game description in Play Store 
- [ ] Check translations
- [x] fix shadow in splash screen
- [x] revise main menu background graphic
- [x] elongate Shinkansen in main menu
- [x] revise the header and "holder" in themes and game settings screen
- [x] add texture to green background in themes and game settings
- [ ] AI fix: check train-train collision when on different paths
- [x] AI fix: check suitable start placement
- [x] Revise start placement icon/button
- [x] Revise in-game selected settings indicator
- [x] "Next" text in-game is not translated
- [x] add 2 more obstacle assets and choose randomly
- [x] Fix "play" button jumps back after pressed
- [x] one path has an issue (probably 1-7)
- [x] Fix #10 
- [ ] Add label "tiles" when displaying distance
- [x] For collision check overlap not corner inside other
- [ ] Sometimes the next AI is not triggered
- [x] Add indicator for upcoming themes

Skip:
- [ ] add game border graphic
